PUT http://localhost:5092/api/TodoItems/1
Content-Type: application/json

{
  "id": 1,
  "name": "Updated Item",
  "isComplete": true
}

###

DELETE http://localhost:5092/api/TodoItems/1

###

POST http://localhost:5092/api/TodoItems
Content-Type: application/json

{
  "id": 13,
  "name": "Updated Item",
  "isComplete": true,
  "secret": "This is a secret!!"
}