namespace JobTrackerApi.Models;
using System.ComponentModel.DataAnnotations;
/// <summary>
/// DTO for creating a new document associated with a job application
/// </summary>
public class DocumentDTO {
    [Required]
    public required IFormFile File { get; set; }

    public DocumentType Type { get; set; } = DocumentType.Other;

    [MaxLength(ValidationConstants.MaxDocumentNameLength)]
    public string? Name { get; set; } // optional override

    /// <summary>
    /// Returns the extension-qualified unique filename to be used for storage.
    /// Call this before <see cref="SaveAsync"/> so the same name is passed to both.
    /// </summary>
    public string GenerateStoredName() {
        string extension = Path.GetExtension(File.FileName).ToLowerInvariant();
        return $"{Guid.NewGuid()}{extension}";
    }

    /// <summary>
    /// Converts this DTO to a Document entity.
    /// </summary>
    /// <param name="jobId">The ID of the job this document belongs to.</param>
    /// <param name="storedName">The unique filename generated by <see cref="GenerateStoredName"/>.</param>
    /// <param name="storageKey">The key returned by <see cref="IStorageService.SaveAsync"/>.</param>
    public Document ToDocument(int jobId, string storedName, string storageKey) {
        // Do not use the FileName property of IFormFile, removes the path from the file name
        // https://learn.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-10.0#validation
        string extension = Path.GetExtension(File.FileName).ToLowerInvariant();
        string rawName = Path.GetFileName(Name ?? File.FileName);
        string displayName = Path.HasExtension(rawName) ? rawName : rawName + extension;

        return new Document {
            Type = Type,
            Name = displayName,
            StoredName = storedName,
            StorageKey = storageKey,
            CreatedAt = DateTime.UtcNow, // use UTC for consistency
            JobId = jobId
        };
    }

    /// <summary>
    /// Checks if the uploaded file has a valid extension.
    /// </summary>
    /// <returns>>true if the file has an allowed extension; otherwise, false.</returns>
    public bool HasValidExtension() {
        // file extension need to be consistent, regardless of the culture
        var extension = Path.GetExtension(File.FileName).ToLowerInvariant();
        return ValidationConstants.AllowedExtensions.Contains(extension);
    }

    /// <summary>
    /// Checks if the uploaded file does not exceed the maximum allowed size.
    /// </summary>
    /// <returns>true if the file size is within the limit; otherwise, false.</returns
    public bool HasValidSize() {
        return File.Length <= ValidationConstants.MaxFileSize;
    }

}
