// Suggestion pools for the profile tag sections' autocomplete.
// Data-only: TagInput reads each as a flat string[] and only *suggests* — input is never restricted to these.
import ISO6391 from "iso-639-1"

// Tech and software industry roles only; suggestions are non-exhaustive for other fields.
export const TARGET_ROLE_SUGGESTIONS: string[] = [
  // Software Engineering
  "Software Engineer",
  "Software Developer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Web Developer",
  "Mobile Developer",
  "Android Developer",
  "iOS Developer",
  "Embedded Software Engineer",
  "Firmware Engineer",
  "Game Developer",
  "React Developer",
  "Angular Developer",
  "Vue Developer",
  "Node.js Developer",
  "Java Developer",
  "Python Developer",
  "C# Developer",
  "JavaScript Developer",
  "TypeScript Developer",
  "Go Developer",
  "Rust Developer",
  "Ruby Developer",
  "PHP Developer",
  "Kotlin Developer",
  "Swift Developer",
  "ASP.NET Developer",
  // Seniority / IC track
  "Junior Software Engineer",
  "Senior Software Engineer",
  "Staff Engineer",
  "Principal Engineer",
  "Distinguished Engineer",
  "Software Architect",
  "Solutions Architect",
  "Enterprise Architect",
  // Data / Analytics
  "Data Analyst",
  "Data Engineer",
  "Data Scientist",
  "Analytics Engineer",
  "Business Analyst",
  "Business Intelligence Developer",
  "BI Analyst",
  "ETL Developer",
  "Big Data Engineer",
  "Data Warehouse Engineer",
  "Data Architect",
  // AI / ML
  "Machine Learning Engineer",
  "AI Engineer",
  "MLOps Engineer",
  "AI Research Scientist",
  "NLP Engineer",
  "Computer Vision Engineer",
  "Deep Learning Engineer",
  "Generative AI Engineer",
  "LLM Engineer",
  // DevOps / Cloud / Platform / SRE
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Platform Engineer",
  "Cloud Engineer",
  "Cloud Architect",
  "Infrastructure Engineer",
  "Systems Administrator",
  "Systems Engineer",
  "Network Engineer",
  "Database Administrator",
  "AWS Engineer",
  "Azure Engineer",
  "GCP Engineer",
  "Kubernetes Engineer",
  "Build Engineer",
  "Release Engineer",
  "DevSecOps Engineer",
  // Product & Project
  "Product Manager",
  "Senior Product Manager",
  "Principal Product Manager",
  "Technical Product Manager",
  "Product Owner",
  "Project Manager",
  "Technical Project Manager",
  "Program Manager",
  "Scrum Master",
  "Agile Coach",
  "Growth Product Manager",
  // UX / Design
  "UX Designer",
  "UI Designer",
  "Product Designer",
  "UX Researcher",
  "Interaction Designer",
  "Visual Designer",
  "Graphic Designer",
  "Web Designer",
  "Design Systems Designer",
  // QA / Testing
  "QA Engineer",
  "QA Analyst",
  "Test Engineer",
  "Test Automation Engineer",
  "Software Test Engineer",
  "Performance Test Engineer",
  // Security
  "Security Engineer",
  "Application Security Engineer",
  "Cybersecurity Analyst",
  "Security Architect",
  "Penetration Tester",
  "SOC Analyst",
  "Information Security Analyst",
  // Engineering leadership
  "Tech Lead",
  "Engineering Manager",
  "Director of Engineering",
  "VP of Engineering",
  "Head of Engineering",
  "Chief Technology Officer",
  "Chief Information Officer",
  // Developer-adjacent
  "Technical Writer",
  "Developer Advocate",
  "Developer Relations Engineer",
  "Solutions Engineer",
  "Integration Engineer",
  "API Developer",
  "Blockchain Developer",
  "AR/VR Developer",
  "Robotics Engineer",
]

export const SKILL_SUGGESTIONS: string[] = [
  "TypeScript",
  "React",
  "C#",
  ".NET",
  "PostgreSQL",
]

export const CERTIFICATION_SUGGESTIONS: string[] = [
  "AWS Certified Solutions Architect",
  "Azure Fundamentals (AZ-900)",
  "Certified Kubernetes Administrator (CKA)",
]

// All ISO 639-1 English language names (~184), computed once at module load. Custom entries still allowed.
export const LANGUAGE_SUGGESTIONS: string[] = ISO6391.getAllNames()

// PLACEHOLDER — representative universities only.
// Full list from Hipolabs world_universities_and_domains.json added in sub-step I.
export const INSTITUTION_SUGGESTIONS: string[] = [
  "University of Auckland",
  "University of Melbourne",
  "University of Sydney",
  "Massachusetts Institute of Technology",
  "Stanford University",
]

export const DEGREE_SUGGESTIONS: string[] = [
  // Bachelor
  "Bachelor of Science",
  "Bachelor of Arts",
  "Bachelor of Engineering",
  "Bachelor of Commerce",
  "Bachelor of Education",
  "Bachelor of Laws",
  "Bachelor of Architecture",
  "Bachelor of Nursing",
  "Bachelor of Fine Arts",
  "Bachelor of Information Technology",
  "Bachelor of Science in Computer Science",
  "Bachelor of Science in Software Engineering",
  "Bachelor of Business Administration",
  // Master
  "Master of Science",
  "Master of Arts",
  "Master of Engineering",
  "Master of Business Administration",
  "Master of Laws",
  "Master of Education",
  "Master of Public Health",
  "Master of Fine Arts",
  "Master of Information Technology",
  "Master of Science in Computer Science",
  "Master of Science in Data Science",
  // Doctoral
  "Doctor of Philosophy",
  "Doctor of Medicine",
  "Juris Doctor",
  "Doctor of Engineering",
  // Associate / Diploma
  "Associate of Science",
  "Associate of Arts",
  "Graduate Diploma",
  "Postgraduate Diploma",
  // High school
  "High School Diploma",
]
