// Suggestion pools for the profile tag sections' autocomplete.
// Data-only: TagInput reads each as a flat string[] and only *suggests* — input is never restricted to these.
import ISO6391 from "iso-639-1"

// Tech and software industry roles only; suggestions are non-exhaustive for other fields.
export const TARGET_ROLE_SUGGESTIONS: string[] = [
  // Software Engineering
  "Software Engineer",
  "Software Developer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Web Developer",
  "Mobile Developer",
  "Android Developer",
  "iOS Developer",
  "Embedded Software Engineer",
  "Firmware Engineer",
  "Game Developer",
  "React Developer",
  "Angular Developer",
  "Vue Developer",
  "Node.js Developer",
  "Java Developer",
  "Python Developer",
  "C# Developer",
  "JavaScript Developer",
  "TypeScript Developer",
  "Go Developer",
  "Rust Developer",
  "Ruby Developer",
  "PHP Developer",
  "Kotlin Developer",
  "Swift Developer",
  "ASP.NET Developer",
  // Seniority / IC track
  "Junior Software Engineer",
  "Senior Software Engineer",
  "Staff Engineer",
  "Principal Engineer",
  "Distinguished Engineer",
  "Software Architect",
  "Solutions Architect",
  "Enterprise Architect",
  // Data / Analytics
  "Data Analyst",
  "Data Engineer",
  "Data Scientist",
  "Analytics Engineer",
  "Business Analyst",
  "Business Intelligence Developer",
  "BI Analyst",
  "ETL Developer",
  "Big Data Engineer",
  "Data Warehouse Engineer",
  "Data Architect",
  // AI / ML
  "Machine Learning Engineer",
  "AI Engineer",
  "MLOps Engineer",
  "AI Research Scientist",
  "NLP Engineer",
  "Computer Vision Engineer",
  "Deep Learning Engineer",
  "Generative AI Engineer",
  "LLM Engineer",
  // DevOps / Cloud / Platform / SRE
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Platform Engineer",
  "Cloud Engineer",
  "Cloud Architect",
  "Infrastructure Engineer",
  "Systems Administrator",
  "Systems Engineer",
  "Network Engineer",
  "Database Administrator",
  "AWS Engineer",
  "Azure Engineer",
  "GCP Engineer",
  "Kubernetes Engineer",
  "Build Engineer",
  "Release Engineer",
  "DevSecOps Engineer",
  // Product & Project
  "Product Manager",
  "Senior Product Manager",
  "Principal Product Manager",
  "Technical Product Manager",
  "Product Owner",
  "Project Manager",
  "Technical Project Manager",
  "Program Manager",
  "Scrum Master",
  "Agile Coach",
  "Growth Product Manager",
  // UX / Design
  "UX Designer",
  "UI Designer",
  "Product Designer",
  "UX Researcher",
  "Interaction Designer",
  "Visual Designer",
  "Graphic Designer",
  "Web Designer",
  "Design Systems Designer",
  // QA / Testing
  "QA Engineer",
  "QA Analyst",
  "Test Engineer",
  "Test Automation Engineer",
  "Software Test Engineer",
  "Performance Test Engineer",
  // Security
  "Security Engineer",
  "Application Security Engineer",
  "Cybersecurity Analyst",
  "Security Architect",
  "Penetration Tester",
  "SOC Analyst",
  "Information Security Analyst",
  // Engineering leadership
  "Tech Lead",
  "Engineering Manager",
  "Director of Engineering",
  "VP of Engineering",
  "Head of Engineering",
  "Chief Technology Officer",
  "Chief Information Officer",
  // Developer-adjacent
  "Technical Writer",
  "Developer Advocate",
  "Developer Relations Engineer",
  "Solutions Engineer",
  "Integration Engineer",
  "API Developer",
  "Blockchain Developer",
  "AR/VR Developer",
  "Robotics Engineer",
]

// Tech and software skills only; non-exhaustive for non-technical fields.
export const SKILL_SUGGESTIONS: string[] = [
  // Programming languages
  "Python", "JavaScript", "TypeScript", "Java", "C#", "C++", "C",
  "Go", "Rust", "Ruby", "PHP", "Kotlin", "Swift", "Scala", "R",
  "Dart", "Elixir", "Haskell", "Lua", "Perl", "MATLAB", "Bash",
  "PowerShell", "SQL",
  // Web — frontend
  "HTML", "CSS", "React", "Angular", "Vue.js", "Svelte", "Next.js",
  "Nuxt.js", "Remix", "Tailwind CSS", "Bootstrap", "Sass", "jQuery",
  "Redux", "Zustand", "Vite", "Webpack",
  // Web — backend
  "Node.js", "Express", "NestJS", "FastAPI", "Django", "Flask",
  "Spring Boot", "ASP.NET Core", "Laravel", "Ruby on Rails",
  "Gin", "Fiber", "Actix",
  // Mobile
  "React Native", "Flutter", "SwiftUI", "Jetpack Compose",
  "Xamarin", "Ionic",
  // Databases
  "PostgreSQL", "MySQL", "SQLite", "SQL Server", "Oracle",
  "MongoDB", "Redis", "Cassandra", "DynamoDB", "Elasticsearch",
  "Neo4j", "InfluxDB", "Supabase", "Firebase", "Firestore",
  // Cloud & infrastructure
  "AWS", "Azure", "Google Cloud Platform", "Terraform", "Pulumi",
  "CloudFormation", "Docker", "Kubernetes", "Helm", "Ansible",
  "Linux", "Nginx", "Apache",
  // CI/CD & DevOps
  "GitHub Actions", "GitLab CI", "Jenkins", "CircleCI",
  "ArgoCD", "Datadog", "Prometheus", "Grafana",
  // Data & analytics
  "pandas", "NumPy", "scikit-learn", "Apache Spark", "Apache Kafka",
  "Apache Airflow", "dbt", "Snowflake", "Databricks", "BigQuery",
  "Tableau", "Power BI", "Looker",
  // AI / ML / LLM
  "TensorFlow", "PyTorch", "Keras", "Hugging Face", "LangChain",
  "LlamaIndex", "OpenAI API", "RAG", "Vector Databases",
  "Computer Vision", "NLP", "Deep Learning", "Reinforcement Learning",
  // Testing
  "Jest", "Vitest", "pytest", "JUnit", "Mocha", "Cypress",
  "Playwright", "Selenium", "xUnit", "Moq",
  // Architecture & practices
  "REST APIs", "GraphQL", "gRPC", "WebSockets", "WebAssembly",
  "Microservices", "Event-Driven Architecture", "Domain-Driven Design",
  "Test-Driven Development", "Agile", "Scrum", "Kanban",
  "CI/CD", "DevOps", "DevSecOps", "Site Reliability Engineering",
  "Clean Architecture", "SOLID Principles",
  // Security
  "OAuth 2.0", "JWT", "OpenID Connect", "OWASP", "SSL/TLS",
  "Penetration Testing", "Cryptography",
  // Tools & platforms
  "Git", "GitHub", "GitLab", "Bitbucket", "Jira", "Confluence",
  "Figma", "Postman", "VS Code", "OpenAPI", "Swagger",
  "Electron", "WebAssembly",
]

// Common professional certifications across tech, finance, HR, marketing, and operations.
export const CERTIFICATION_SUGGESTIONS: string[] = [
  // AWS
  "AWS Certified Cloud Practitioner",
  "AWS Certified Solutions Architect – Associate",
  "AWS Certified Solutions Architect – Professional",
  "AWS Certified Developer – Associate",
  "AWS Certified SysOps Administrator – Associate",
  "AWS Certified DevOps Engineer – Professional",
  "AWS Certified Data Engineer – Associate",
  "AWS Certified Machine Learning – Specialty",
  "AWS Certified Security – Specialty",
  "AWS Certified Advanced Networking – Specialty",
  // Microsoft Azure
  "Microsoft Azure Fundamentals (AZ-900)",
  "Microsoft Azure Administrator (AZ-104)",
  "Microsoft Azure Developer (AZ-204)",
  "Microsoft Azure Solutions Architect Expert (AZ-305)",
  "Microsoft Azure DevOps Engineer Expert (AZ-400)",
  "Microsoft Azure AI Engineer Associate (AI-102)",
  "Microsoft Azure Data Engineer Associate (DP-203)",
  "Microsoft Azure Data Scientist Associate (DP-100)",
  "Microsoft Azure Security Engineer Associate (AZ-500)",
  "Microsoft Cybersecurity Architect (SC-100)",
  "Microsoft Security Operations Analyst (SC-200)",
  "Microsoft 365 Fundamentals (MS-900)",
  "Microsoft 365 Administrator (MS-102)",
  "Microsoft Power BI Data Analyst (PL-300)",
  // Google Cloud
  "Google Associate Cloud Engineer",
  "Google Professional Cloud Architect",
  "Google Professional Cloud Developer",
  "Google Professional Data Engineer",
  "Google Professional Cloud DevOps Engineer",
  "Google Professional Cloud Security Engineer",
  "Google Professional Machine Learning Engineer",
  // CompTIA
  "CompTIA IT Fundamentals (ITF+)",
  "CompTIA A+",
  "CompTIA Network+",
  "CompTIA Security+",
  "CompTIA Cloud+",
  "CompTIA Linux+",
  "CompTIA Data+",
  "CompTIA CySA+",
  "CompTIA PenTest+",
  "CompTIA CASP+",
  // Cisco
  "Cisco CCNA",
  "Cisco CCNP",
  "Cisco CCIE",
  "Cisco CyberOps Associate",
  "Cisco DevNet Associate",
  // Security — ISC2
  "CISSP",
  "CCSP (Certified Cloud Security Professional)",
  "SSCP",
  // Security — ISACA
  "CISM",
  "CISA",
  "CRISC",
  "CGEIT",
  // Security — EC-Council & Other
  "CEH (Certified Ethical Hacker)",
  "CCISO (Certified Chief Information Security Officer)",
  "OSCP (Offensive Security Certified Professional)",
  // Security — GIAC
  "GIAC GSEC",
  "GIAC GCIH",
  "GIAC GPEN",
  "GIAC GWAPT",
  // Data Privacy
  "CIPP/E",
  "CIPP/US",
  "CIPM",
  "CIPT",
  // Kubernetes & DevOps
  "CKA (Certified Kubernetes Administrator)",
  "CKAD (Certified Kubernetes Application Developer)",
  "CKS (Certified Kubernetes Security Specialist)",
  "HashiCorp Terraform Associate",
  "Docker Certified Associate",
  "Red Hat Certified System Administrator (RHCSA)",
  "Red Hat Certified Engineer (RHCE)",
  // GitHub
  "GitHub Foundations",
  "GitHub Actions",
  "GitHub Advanced Security",
  "GitHub Copilot",
  // Networking & Infrastructure
  "Palo Alto PCNSA",
  "Palo Alto PCNSE",
  "VMware VCP (vSphere Foundation)",
  // Data & Analytics
  "Databricks Certified Data Engineer Associate",
  "Databricks Certified Machine Learning Professional",
  "Snowflake SnowPro Core",
  "Tableau Desktop Specialist",
  "dbt Analytics Engineering Certification",
  // AI / ML
  "TensorFlow Developer Certificate",
  "Certified AI Practitioner (CompTIA)",
  // SAP
  "SAP Certified Application Associate",
  "SAP Certified Technology Associate",
  // Salesforce
  "Salesforce Certified Administrator",
  "Salesforce Platform Developer I",
  "Salesforce Platform App Builder",
  "Salesforce Sales Cloud Consultant",
  "Salesforce Service Cloud Consultant",
  // ServiceNow
  "ServiceNow Certified System Administrator",
  "ServiceNow Certified Application Developer",
  // Project Management
  "PMP (Project Management Professional)",
  "CAPM (Certified Associate in Project Management)",
  "PMI-ACP (Agile Certified Practitioner)",
  "PMI-PBA (Professional in Business Analysis)",
  "PMI-RMP (Risk Management Professional)",
  "PRINCE2 Foundation",
  "PRINCE2 Practitioner",
  // Agile & Scrum
  "CSM (Certified Scrum Master)",
  "CSPO (Certified Scrum Product Owner)",
  "CSP-SM",
  "CSP-PO",
  "SAFe Agilist",
  "SAFe Practitioner",
  // IT Service Management
  "ITIL 4 Foundation",
  "ITIL 4 Practitioner",
  // Finance & Accounting
  "CPA (Certified Public Accountant)",
  "CFA (Chartered Financial Analyst)",
  "CMA (Certified Management Accountant)",
  "CFP (Certified Financial Planner)",
  "FRM (Financial Risk Manager)",
  "CIA (Certified Internal Auditor)",
  "ACCA",
  "CA (Chartered Accountant)",
  "CAIA (Chartered Alternative Investment Analyst)",
  "CFE (Certified Fraud Examiner)",
  // Human Resources
  "SHRM-CP",
  "SHRM-SCP",
  "PHR (Professional in Human Resources)",
  "SPHR (Senior Professional in Human Resources)",
  "GPHR (Global Professional in Human Resources)",
  "aPHR (Associate Professional in Human Resources)",
  // Marketing & Digital
  "Google Analytics Certification",
  "Google Ads Certification",
  "HubSpot Inbound Marketing Certification",
  "HubSpot Content Marketing Certification",
  "HubSpot Digital Marketing Certification",
  "Meta Blueprint Certification",
  // Supply Chain & Operations
  "APICS CPIM",
  "APICS CSCP (Certified Supply Chain Professional)",
  "CLTD (Certified in Logistics, Transportation and Distribution)",
  // Quality & Lean
  "Lean Six Sigma Green Belt",
  "Lean Six Sigma Black Belt",
  "Six Sigma Green Belt",
  "Six Sigma Black Belt",
  // Engineering & Other
  "PE (Professional Engineer)",
  "LEED AP",
]

// All ISO 639-1 English language names (~184), computed once at module load. Custom entries still allowed.
export const LANGUAGE_SUGGESTIONS: string[] = ISO6391.getAllNames()

// PLACEHOLDER — representative universities only.
// Full list from Hipolabs world_universities_and_domains.json added in sub-step I.
export const INSTITUTION_SUGGESTIONS: string[] = [
  "University of Auckland",
  "University of Melbourne",
  "University of Sydney",
  "Massachusetts Institute of Technology",
  "Stanford University",
]

export const DEGREE_SUGGESTIONS: string[] = [
  // Bachelor
  "Bachelor of Science",
  "Bachelor of Arts",
  "Bachelor of Engineering",
  "Bachelor of Commerce",
  "Bachelor of Education",
  "Bachelor of Laws",
  "Bachelor of Architecture",
  "Bachelor of Nursing",
  "Bachelor of Fine Arts",
  "Bachelor of Information Technology",
  "Bachelor of Science in Computer Science",
  "Bachelor of Science in Software Engineering",
  "Bachelor of Business Administration",
  // Master
  "Master of Science",
  "Master of Arts",
  "Master of Engineering",
  "Master of Business Administration",
  "Master of Laws",
  "Master of Education",
  "Master of Public Health",
  "Master of Fine Arts",
  "Master of Information Technology",
  "Master of Science in Computer Science",
  "Master of Science in Data Science",
  // Doctoral
  "Doctor of Philosophy",
  "Doctor of Medicine",
  "Juris Doctor",
  "Doctor of Engineering",
  // Associate / Diploma
  "Associate of Science",
  "Associate of Arts",
  "Graduate Diploma",
  "Postgraduate Diploma",
  // High school
  "High School Diploma",
]
